const restaurants = [
    {
      info: {
        id: "24162",
        name: "Domino's Pizza",
        cloudinaryImageId: "d0450ce1a6ba19ea60cd724471ed54a8",
        locality: "Rohini",
        areaName: "Rohini",
        costForTwo: "₹400 for two",
        cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
        avgRating: 4.5,
        parentId: "2456",
        avgRatingString: "4.5",
        totalRatingsString: "10K+",
        sla: {
          deliveryTime: 25,
          lastMileTravel: 2,
          serviceability: "SERVICEABLE",
          slaString: "25 mins",
          lastMileTravelString: "2.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-04-14 03:00:00",
          opened: true,
        },
        badges: {
          imageBadges: [
            {
              imageId: "Rxawards/_CATEGORY-Pizza.png",
              description: "Delivery!",
            },
          ],
        },
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {
              badgeObject: [
                {
                  attributes: {
                    description: "Delivery!",
                    imageId: "Rxawards/_CATEGORY-Pizza.png",
                  },
                },
              ],
            },
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹50",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-a4084667-e7b5-4267-8258-cbe2823cb885",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/dominos-pizza-rohini-delhi-24162",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "20970",
        name: "Oven Story Pizza - Standout Toppings",
        cloudinaryImageId:
          "RX_THUMBNAIL/IMAGES/VENDOR/2024/4/5/66682fca-8a51-4864-91ee-e0e3edf87884_20970.JPG",
        locality: "Sector 8",
        areaName: "Rohini",
        costForTwo: "₹400 for two",
        cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
        avgRating: 4.1,
        parentId: "3534",
        avgRatingString: "4.1",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 26,
          lastMileTravel: 2.7,
          serviceability: "SERVICEABLE",
          slaString: "21-31 mins",
          lastMileTravelString: "2.7 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-04-14 03:00:00",
          opened: true,
        },
        badges: {
          imageBadges: [
            {
              imageId: "Rxawards/_CATEGORY-Pizza.png",
              description: "Delivery!",
            },
          ],
        },
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {
              badgeObject: [
                {
                  attributes: {
                    description: "Delivery!",
                    imageId: "Rxawards/_CATEGORY-Pizza.png",
                  },
                },
              ],
            },
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹199",
          discountTag: "FLAT DEAL",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-a4084667-e7b5-4267-8258-cbe2823cb885",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/oven-story-pizza-standout-toppings-sector-8-rohini-delhi-20970",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "385874",
        name: "Healthy Food",
        cloudinaryImageId: "s9abvlhedkypp3bvwexu",
        locality: "Nagin Lake",
        areaName: "Paschim Vihar",
        costForTwo: "₹500 for two",
        cuisines: ["Healthy Food"],
        avgRating: 4.8,
        parentId: "14813",
        avgRatingString: "4.8",
        totalRatingsString: "10+",
        sla: {
          deliveryTime: 31,
          lastMileTravel: 3.9,
          serviceability: "SERVICEABLE",
          slaString: "30-35 mins",
          lastMileTravelString: "3.9 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-04-20 00:00:00",
          opened: true,
        },
        badges: {
          textExtendedBadges: [
            {
              iconId: "guiltfree/GF_Logo_android_3x",
              shortDescription: "brand",
              fontColor: "#7E808C",
            },
          ],
        },
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {
              badgeObject: [
                {
                  attributes: {
                    description: "",
                    fontColor: "#7E808C",
                    iconId: "guiltfree/GF_Logo_android_3x",
                    shortDescription: "brand",
                  },
                },
              ],
            },
          },
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-a4084667-e7b5-4267-8258-cbe2823cb885",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/healthy-food-nagin-lake-paschim-vihar-delhi-385874",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "47137",
        name: "Da Pizza Makers",
        cloudinaryImageId: "tyl5lpyee3a0slfxviul",
        locality: "Bhera Enclave",
        areaName: "Paschim Vihar",
        costForTwo: "₹349 for two",
        cuisines: [
          "Pizzas",
          "Pastas",
          "Burgers",
          "Italian",
          "Desserts",
          "Beverages",
        ],
        avgRating: 3.8,
        parentId: "5178",
        avgRatingString: "3.8",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 43,
          lastMileTravel: 3.9,
          serviceability: "SERVICEABLE",
          slaString: "40-45 mins",
          lastMileTravelString: "3.9 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-04-14 04:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "30% OFF",
          subHeader: "UPTO ₹150",
          discountTag: "SAVE BIG",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-a4084667-e7b5-4267-8258-cbe2823cb885",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/da-pizza-makers-bhera-enclave-paschim-vihar-delhi-47137",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "417627",
        name: "Healthy Burgers",
        cloudinaryImageId: "y2uqiib2p1x22lycge8p",
        locality: "Nagin Lake",
        areaName: "Paschim Vihar",
        costForTwo: "₹500 for two",
        cuisines: [
          "Continental",
          "American",
          "Desserts",
          "Mexican",
          "Beverages",
          "Punjabi",
        ],
        avgRating: 5,
        parentId: "94888",
        avgRatingString: "5.0",
        totalRatingsString: "20+",
        sla: {
          deliveryTime: 32,
          lastMileTravel: 3.9,
          serviceability: "SERVICEABLE",
          slaString: "30-35 mins",
          lastMileTravelString: "3.9 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-04-20 00:00:00",
          opened: true,
        },
        badges: {
          textExtendedBadges: [
            {
              iconId: "guiltfree/GF_Logo_android_3x",
              shortDescription: "brand",
              fontColor: "#7E808C",
            },
          ],
        },
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {
              badgeObject: [
                {
                  attributes: {
                    description: "",
                    fontColor: "#7E808C",
                    iconId: "guiltfree/GF_Logo_android_3x",
                    shortDescription: "brand",
                  },
                },
              ],
            },
          },
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-a4084667-e7b5-4267-8258-cbe2823cb885",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/healthy-burgers-nagin-lake-paschim-vihar-delhi-417627",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "385876",
        name: "Late Night Sandwich",
        cloudinaryImageId: "hrlvcf1lm20faz04drvw",
        locality: "Nagin Lake",
        areaName: "Paschim Vihar",
        costForTwo: "₹500 for two",
        cuisines: ["Healthy Food"],
        avgRating: 4.2,
        parentId: "249379",
        avgRatingString: "4.2",
        totalRatingsString: "20+",
        sla: {
          deliveryTime: 49,
          lastMileTravel: 3.9,
          serviceability: "SERVICEABLE",
          slaString: "45-50 mins",
          lastMileTravelString: "3.9 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-04-20 00:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-a4084667-e7b5-4267-8258-cbe2823cb885",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/late-night-sandwich-nagin-lake-paschim-vihar-delhi-385876",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "385870",
        name: "Burger And Sandwich Karol Bagh Wale (TAAL)",
        cloudinaryImageId: "v5wdetfikqatha6c8bxk",
        locality: "Nagin Lake",
        areaName: "Paschim Vihar",
        costForTwo: "₹300 for two",
        cuisines: ["Continental", "Fast Food"],
        avgRating: 4.7,
        parentId: "242800",
        avgRatingString: "4.7",
        totalRatingsString: "50+",
        sla: {
          deliveryTime: 52,
          lastMileTravel: 3.9,
          serviceability: "SERVICEABLE",
          slaString: "50-55 mins",
          lastMileTravelString: "3.9 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-04-14 11:59:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-a4084667-e7b5-4267-8258-cbe2823cb885",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/burger-and-sandwich-karol-bagh-wale-taal-nagin-lake-paschim-vihar-delhi-385870",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "385872",
        name: "Late Night Burger",
        cloudinaryImageId: "sbwuxg2udhfhgacfhdrs",
        locality: "Punjabi Bagh",
        areaName: "Paschim Vihar",
        costForTwo: "₹500 for two",
        cuisines: ["Healthy Food"],
        avgRating: 4.1,
        parentId: "249377",
        avgRatingString: "4.1",
        totalRatingsString: "20+",
        sla: {
          deliveryTime: 47,
          lastMileTravel: 3.9,
          serviceability: "SERVICEABLE",
          slaString: "45-50 mins",
          lastMileTravelString: "3.9 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-04-20 00:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-a4084667-e7b5-4267-8258-cbe2823cb885",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/late-night-burger-punjabi-bagh-paschim-vihar-delhi-385872",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "64160",
        name: "Hungry Fukrey",
        cloudinaryImageId: "y8xfrocwg1lfslyw2czj",
        locality: "Punjabi Bagh",
        areaName: "Paschim Vihar",
        costForTwo: "₹300 for two",
        cuisines: ["Continental", "Italian"],
        avgRating: 4.2,
        parentId: "22368",
        avgRatingString: "4.2",
        totalRatingsString: "100+",
        sla: {
          deliveryTime: 37,
          lastMileTravel: 3.9,
          serviceability: "SERVICEABLE",
          slaString: "35-40 mins",
          lastMileTravelString: "3.9 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-04-20 00:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-a4084667-e7b5-4267-8258-cbe2823cb885",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/hungry-fukrey-punjabi-bagh-paschim-vihar-delhi-64160",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
        info: {
          id: "555831",
          name: "Only At 129",
          cloudinaryImageId: "a6c5d1936ff122a825c43524225adc9f",
          locality: "CSC Market",
          areaName: "Paschim Vihar",
          costForTwo: "₹400 for two",
          cuisines: ["Chaat", "Chinese", "North Indian", "Snacks"],
          avgRating: 3.7,
          parentId: "334442",
          avgRatingString: "3.7",
          totalRatingsString: "1K+",
          sla: {
            deliveryTime: 34,
            lastMileTravel: 4.9,
            serviceability: "SERVICEABLE",
            slaString: "30-35 mins",
            lastMileTravelString: "4.9 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseTime: "2024-04-14 04:00:00",
            opened: true,
          },
          badges: {},
          isOpen: true,
          type: "F",
          badgesV2: {
            entityBadges: {
              imageBased: {},
              textBased: {},
              textExtendedBadges: {},
            },
          },
          aggregatedDiscountInfoV3: {
            header: "60% OFF",
            subHeader: "UPTO ₹120",
          },
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          differentiatedUi: {
            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
            differentiatedUiMediaDetails: {
              mediaType: "ADS_MEDIA_ENUM_IMAGE",
              lottie: {},
              video: {},
            },
          },
          reviewsSummary: {},
          displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
          restaurantOfferPresentationInfo: {},
        },
        analytics: {
          context: "seo-data-752f29b8-b843-49f5-b936-8526475f974e",
        },
        cta: {
          link: "https://www.swiggy.com/restaurants/only-at-129-csc-market-paschim-vihar-delhi-555831",
          text: "RESTAURANT_MENU",
          type: "WEBLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
      },
      {
        info: {
          id: "34074",
          name: "Kapoor Dhaba",
          cloudinaryImageId: "xn5qifxjfrfi1b3rhv1s",
          locality: "Peeragarhi Camp",
          areaName: "Punjabi Bagh",
          costForTwo: "₹200 for two",
          cuisines: ["North Indian", "Desserts", "Beverages"],
          avgRating: 4.2,
          veg: true,
          parentId: "114884",
          avgRatingString: "4.2",
          totalRatingsString: "1K+",
          sla: {
            deliveryTime: 31,
            lastMileTravel: 4.8,
            serviceability: "SERVICEABLE",
            slaString: "30-35 mins",
            lastMileTravelString: "4.8 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseTime: "2024-04-14 05:00:00",
            opened: true,
          },
          badges: {
            imageBadges: [
              {
                imageId: "v1695133679/badges/Pure_Veg111.png",
                description: "pureveg",
              },
            ],
          },
          isOpen: true,
          aggregatedDiscountInfoV2: {},
          type: "F",
          badgesV2: {
            entityBadges: {
              imageBased: {
                badgeObject: [
                  {
                    attributes: {
                      description: "pureveg",
                      imageId: "v1695133679/badges/Pure_Veg111.png",
                    },
                  },
                ],
              },
              textBased: {},
              textExtendedBadges: {},
            },
          },
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          differentiatedUi: {
            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
            differentiatedUiMediaDetails: {
              mediaType: "ADS_MEDIA_ENUM_IMAGE",
              lottie: {},
              video: {},
            },
          },
          reviewsSummary: {},
          displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
          restaurantOfferPresentationInfo: {},
        },
        analytics: {
          context: "seo-data-752f29b8-b843-49f5-b936-8526475f974e",
        },
        cta: {
          link: "https://www.swiggy.com/restaurants/kapoor-dhaba-peeragarhi-camp-punjabi-bagh-delhi-34074",
          text: "RESTAURANT_MENU",
          type: "WEBLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
      },
      {
        info: {
          id: "789602",
          name: "Handi 47",
          cloudinaryImageId: "f60a0596a76581b140ea724a02b7805b",
          locality: "Jwala Heri",
          areaName: "Paschim Vihar",
          costForTwo: "₹250 for two",
          cuisines: ["North Indian", "Snacks", "Beverages"],
          avgRating: 4.1,
          parentId: "417357",
          avgRatingString: "4.1",
          totalRatingsString: "100+",
          sla: {
            deliveryTime: 36,
            lastMileTravel: 6.2,
            serviceability: "SERVICEABLE",
            slaString: "35-40 mins",
            lastMileTravelString: "6.2 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseTime: "2024-04-14 23:59:00",
            opened: true,
          },
          badges: {},
          isOpen: true,
          type: "F",
          badgesV2: {
            entityBadges: {
              imageBased: {},
              textBased: {},
              textExtendedBadges: {},
            },
          },
          aggregatedDiscountInfoV3: {
            header: "60% OFF",
            subHeader: "UPTO ₹120",
          },
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          differentiatedUi: {
            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
            differentiatedUiMediaDetails: {
              mediaType: "ADS_MEDIA_ENUM_IMAGE",
              lottie: {},
              video: {},
            },
          },
          reviewsSummary: {},
          displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
          isNewlyOnboarded: true,
          restaurantOfferPresentationInfo: {},
        },
        analytics: {
          context: "seo-data-752f29b8-b843-49f5-b936-8526475f974e",
        },
        cta: {
          link: "https://www.swiggy.com/restaurants/handi-47-jwala-heri-paschim-vihar-delhi-789602",
          text: "RESTAURANT_MENU",
          type: "WEBLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
      },
      {
        info: {
          id: "865325",
          name: "24Seven",
          cloudinaryImageId:
            "RX_THUMBNAIL/IMAGES/VENDOR/2024/4/2/247fec02-0d5d-4c96-a265-7f07744abdc6_865325.jpg",
          locality: "Paschim Vihar",
          areaName: "Paschim Vihar",
          costForTwo: "₹300 for two",
          cuisines: [
            "Bakery",
            "Cakes and Pastries",
            "Burgers",
            "Indian",
            "Pizzas",
            "Fast Food",
            "Snacks",
          ],
          parentId: "3773",
          avgRatingString: "NEW",
          sla: {
            deliveryTime: 35,
            lastMileTravel: 5.6,
            serviceability: "SERVICEABLE",
            slaString: "30-35 mins",
            lastMileTravelString: "5.6 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseTime: "2024-04-14 23:59:00",
            opened: true,
          },
          badges: {},
          isOpen: true,
          aggregatedDiscountInfoV2: {},
          type: "F",
          badgesV2: {
            entityBadges: {
              imageBased: {},
              textBased: {},
              textExtendedBadges: {},
            },
          },
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          differentiatedUi: {
            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
            differentiatedUiMediaDetails: {
              mediaType: "ADS_MEDIA_ENUM_IMAGE",
              lottie: {},
              video: {},
            },
          },
          reviewsSummary: {},
          displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
          isNewlyOnboarded: true,
          restaurantOfferPresentationInfo: {},
        },
        analytics: {
          context: "seo-data-752f29b8-b843-49f5-b936-8526475f974e",
        },
        cta: {
          link: "https://www.swiggy.com/restaurants/24seven-paschim-vihar-delhi-865325",
          text: "RESTAURANT_MENU",
          type: "WEBLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
      },
      {
        info: {
          id: "661359",
          name: "Xero Degrees",
          cloudinaryImageId: "906c0affa7d8ff78a3e4db88b4433cde",
          locality: "Pushpak Enclave",
          areaName: "Paschim Vihar",
          costForTwo: "₹950 for two",
          cuisines: [
            "Italian-American",
            "Beverages",
            "Chinese",
            "Fast Food",
            "Salads",
          ],
          avgRating: 3.7,
          parentId: "21709",
          avgRatingString: "3.7",
          totalRatingsString: "100+",
          sla: {
            deliveryTime: 36,
            lastMileTravel: 4.9,
            serviceability: "SERVICEABLE",
            slaString: "35-40 mins",
            lastMileTravelString: "4.9 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseTime: "2024-04-14 04:30:00",
            opened: true,
          },
          badges: {},
          isOpen: true,
          aggregatedDiscountInfoV2: {},
          type: "F",
          badgesV2: {
            entityBadges: {
              imageBased: {},
              textBased: {},
              textExtendedBadges: {},
            },
          },
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          differentiatedUi: {
            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
            differentiatedUiMediaDetails: {
              mediaType: "ADS_MEDIA_ENUM_IMAGE",
              lottie: {},
              video: {},
            },
          },
          reviewsSummary: {},
          displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
          restaurantOfferPresentationInfo: {},
        },
        analytics: {
          context: "seo-data-752f29b8-b843-49f5-b936-8526475f974e",
        },
        cta: {
          link: "https://www.swiggy.com/restaurants/xero-degrees-pushpak-enclave-paschim-vihar-delhi-661359",
          text: "RESTAURANT_MENU",
          type: "WEBLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
      },
      {
        info: {
          id: "504341",
          name: "Sardar Ji Late Night Kitchen",
          cloudinaryImageId: "xax24mb5ktl439uewghm",
          locality: "A Block",
          areaName: "Paschim Vihar",
          costForTwo: "₹300 for two",
          cuisines: [
            "North Indian",
            "Punjabi",
            "Chinese",
            "Biryani",
            "Beverages",
            "Tandoor",
            "Indian",
          ],
          avgRating: 4.3,
          parentId: "13225",
          avgRatingString: "4.3",
          totalRatingsString: "500+",
          sla: {
            deliveryTime: 37,
            lastMileTravel: 5,
            serviceability: "SERVICEABLE",
            slaString: "35-40 mins",
            lastMileTravelString: "5.0 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseTime: "2024-04-14 04:00:00",
            opened: true,
          },
          badges: {},
          isOpen: true,
          aggregatedDiscountInfoV2: {},
          type: "F",
          badgesV2: {
            entityBadges: {
              imageBased: {},
              textBased: {},
              textExtendedBadges: {},
            },
          },
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          differentiatedUi: {
            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
            differentiatedUiMediaDetails: {
              mediaType: "ADS_MEDIA_ENUM_IMAGE",
              lottie: {},
              video: {},
            },
          },
          reviewsSummary: {},
          displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
          restaurantOfferPresentationInfo: {},
        },
        analytics: {
          context: "seo-data-752f29b8-b843-49f5-b936-8526475f974e",
        },
        cta: {
          link: "https://www.swiggy.com/restaurants/sardar-ji-late-night-kitchen-a-block-paschim-vihar-delhi-504341",
          text: "RESTAURANT_MENU",
          type: "WEBLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
      },
      {
        info: {
          id: "789611",
          name: "Oh!Hunger",
          cloudinaryImageId: "d270f97263e5e0a99cb99137e4a58c8b",
          locality: "Jwala Heri",
          areaName: "Paschim Vihar",
          costForTwo: "₹250 for two",
          cuisines: ["Fast Food", "Snacks", "Burgers", "Biryani", "Beverages"],
          avgRating: 4.1,
          parentId: "400023",
          avgRatingString: "4.1",
          totalRatingsString: "100+",
          sla: {
            deliveryTime: 38,
            lastMileTravel: 6.2,
            serviceability: "SERVICEABLE",
            slaString: "35-40 mins",
            lastMileTravelString: "6.2 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseTime: "2024-04-14 23:59:00",
            opened: true,
          },
          badges: {},
          isOpen: true,
          type: "F",
          badgesV2: {
            entityBadges: {
              imageBased: {},
              textBased: {},
              textExtendedBadges: {},
            },
          },
          aggregatedDiscountInfoV3: {
            header: "60% OFF",
            subHeader: "UPTO ₹120",
          },
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          differentiatedUi: {
            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
            differentiatedUiMediaDetails: {
              mediaType: "ADS_MEDIA_ENUM_IMAGE",
              lottie: {},
              video: {},
            },
          },
          reviewsSummary: {},
          displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
          isNewlyOnboarded: true,
          restaurantOfferPresentationInfo: {},
        },
        analytics: {
          context: "seo-data-752f29b8-b843-49f5-b936-8526475f974e",
        },
        cta: {
          link: "https://www.swiggy.com/restaurants/oh-hunger-jwala-heri-paschim-vihar-delhi-789611",
          text: "RESTAURANT_MENU",
          type: "WEBLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
      },
      {
        info: {
          id: "792644",
          name: "Khichdi Hub",
          cloudinaryImageId: "ebf0f3e38eb13bdb4f5144490fc63416",
          locality: "Jwala Heri",
          areaName: "Paschim Vihar",
          costForTwo: "₹248 for two",
          cuisines: ["Healthy Food"],
          avgRating: 4.3,
          parentId: "406307",
          avgRatingString: "4.3",
          totalRatingsString: "100+",
          sla: {
            deliveryTime: 38,
            lastMileTravel: 6.2,
            serviceability: "SERVICEABLE",
            slaString: "35-40 mins",
            lastMileTravelString: "6.2 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseTime: "2024-04-14 23:59:00",
            opened: true,
          },
          badges: {},
          isOpen: true,
          type: "F",
          badgesV2: {
            entityBadges: {
              imageBased: {},
              textBased: {},
              textExtendedBadges: {},
            },
          },
          aggregatedDiscountInfoV3: {
            header: "60% OFF",
            subHeader: "UPTO ₹120",
          },
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          differentiatedUi: {
            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
            differentiatedUiMediaDetails: {
              mediaType: "ADS_MEDIA_ENUM_IMAGE",
              lottie: {},
              video: {},
            },
          },
          reviewsSummary: {},
          displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
          isNewlyOnboarded: true,
          restaurantOfferPresentationInfo: {},
        },
        analytics: {
          context: "seo-data-752f29b8-b843-49f5-b936-8526475f974e",
        },
        cta: {
          link: "https://www.swiggy.com/restaurants/khichdi-hub-jwala-heri-paschim-vihar-delhi-792644",
          text: "RESTAURANT_MENU",
          type: "WEBLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
      },
      {
        info: {
          id: "585614",
          name: "The Belgian Waffle Co.",
          cloudinaryImageId: "5116a385bac0548e06c33c08350fbf11",
          locality: "Jwala Heri Road",
          areaName: "Paschim Vihar",
          costForTwo: "₹200 for two",
          cuisines: ["Waffle", "Desserts", "Ice Cream"],
          avgRating: 4.4,
          veg: true,
          parentId: "2233",
          avgRatingString: "4.4",
          totalRatingsString: "500+",
          sla: {
            deliveryTime: 41,
            lastMileTravel: 5,
            serviceability: "SERVICEABLE",
            slaString: "40-45 mins",
            lastMileTravelString: "5.0 km",
            iconType: "ICON_TYPE_EMPTY",
          },
          availability: {
            nextCloseTime: "2024-04-14 04:00:00",
            opened: true,
          },
          badges: {
            imageBadges: [
              {
                imageId: "v1695133679/badges/Pure_Veg111.png",
                description: "pureveg",
              },
            ],
          },
          isOpen: true,
          aggregatedDiscountInfoV2: {},
          type: "F",
          badgesV2: {
            entityBadges: {
              imageBased: {
                badgeObject: [
                  {
                    attributes: {
                      description: "pureveg",
                      imageId: "v1695133679/badges/Pure_Veg111.png",
                    },
                  },
                ],
              },
              textBased: {},
              textExtendedBadges: {},
            },
          },
          orderabilityCommunication: {
            title: {},
            subTitle: {},
            message: {},
            customIcon: {},
          },
          differentiatedUi: {
            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
            differentiatedUiMediaDetails: {
              mediaType: "ADS_MEDIA_ENUM_IMAGE",
              lottie: {},
              video: {},
            },
          },
          reviewsSummary: {},
          displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
          restaurantOfferPresentationInfo: {},
        },
        analytics: {
          context: "seo-data-752f29b8-b843-49f5-b936-8526475f974e",
        },
        cta: {
          link: "https://www.swiggy.com/restaurants/the-belgian-waffle-co-jwala-heri-road-paschim-vihar-delhi-585614",
          text: "RESTAURANT_MENU",
          type: "WEBLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
      },
  ];

 export default restaurants; 